name: fwadapt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9.0
  - pytorch=1.8.0
  - torchvision=0.9.0
  - numpy=1.20.3 
  #- jupyterlab=3.1.10
  #- scikit-learn=0.24.2
  #- matplotlib=3.4.3
  - pip
  - pip:
    - hydra-zen==0.2.0
    - hydra-submitit-launcher==1.1.5
